version: "3.9"

services:
  app:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    container_name: todo_dev_app
    entrypoint: dockerize -timeout 60s -wait tcp://mysql:3306
    command: air -c docker/dev/.air.toml
    environment:
      PRODUCTION: "false"
      GO111MODULE: "on"
      MARIADB_USERNAME: root
      MARIADB_PASSWORD: password
      MARIADB_HOSTNAME: mysql
      MARIADB_DATABASE: todo
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URL: ${GOOGLE_REDIRECT_URL}
      WHITE_LIST: ${WHITE_LIST}
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      SLACK_CHANNEL_ID: ${SLACK_CHANNEL_ID}
      TZ: Asia/Tokyo
    ports:
      - "8010:8010"
    depends_on:
      - mysql
    volumes:
      - ../../:/go/src/github.com/MotoyaAsahina/todo/

  mysql:
    image: mariadb:10.3.9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo
      TZ: Asia/Tokyo
    expose:
      - "3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    links:
      - mysql
    ports:
      - "8006:80"
    volumes:
      - ./phpmyadmin/sessions:/sessions
