name: Release

on:
  workflow_dispatch:

env:
  IMAGE_NAME: todo

jobs:
  image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Dockerfile
        run: |
          docker buildx build --platform linux/amd64 -t ${{ env.IMAGE_NAME }}:latest --output type=tar,dest=${{ env.IMAGE_NAME }}.tar .
      - name: Upload image
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.IMAGE_NAME }}.tar
          path: ${{ env.IMAGE_NAME }}.tar
